### ISSUE TITLE
Virtual attributes

### ISSUE THREAD

**Issue by ppoetsma** [synobsys/mendix-ObjectBackupRestore#1]
Hi,

I am testing your module and it seems that it backups virtual attributes that it tries to restore again. Stack trace is below.

Regards,
Paul

com.mendix.modules.microflowengine.MicroflowException: com.mendix.core.CoreRuntimeException: java.lang.RuntimeException: com.mendix.core.CoreRuntimeException: A virtual primitive cannot be assigned a value, as it represents an action
	at ObjectBackupRestore.IVK_Backup_RestoreObjects (JavaAction : 'Call 'RestoreObjectsAction'')

Advanced stacktrace:
	at com.mendix.modules.microflowengine.MicroflowUtil.processException(SourceFile:158)

Caused by: com.mendix.core.CoreException: com.mendix.core.CoreRuntimeException: java.lang.RuntimeException: com.mendix.core.CoreRuntimeException: A virtual primitive cannot be assigned a value, as it represents an action
	at com.mendix.core.component.InternalCore.execute(SourceFile:274)

Caused by: com.mendix.core.CoreRuntimeException: java.lang.RuntimeException: com.mendix.core.CoreRuntimeException: A virtual primitive cannot be assigned a value, as it represents an action
	at com.mendix.core.actionmanagement.ActionManager.executeSync(SourceFile:216)

Caused by: java.lang.RuntimeException: com.mendix.core.CoreRuntimeException: A virtual primitive cannot be assigned a value, as it represents an action
	at objectbackuprestore.RestoreObjectsImpl.restoreObjects(RestoreObjectsImpl.java:275)
	at objectbackuprestore.actions.RestoreObjectsAction.executeAction(RestoreObjectsAction.java:46)
	at objectbackuprestore.actions.RestoreObjectsAction.executeAction(RestoreObjectsAction.java:21)
	at com.mendix.systemwideinterfaces.core.UserAction.execute(SourceFile:53)
	at com.mendix.core.actionmanagement.CoreAction.doCall(SourceFile:291)
	at com.mendix.core.actionmanagement.CoreAction.call(SourceFile:276)
	at com.mendix.core.actionmanagement.ActionManager.executeSync(SourceFile:205)
	at com.mendix.core.component.InternalCore.execute(SourceFile:262)
	at com.mendix.hx.execute(SourceFile:42)
	at com.mendix.ig.a(SourceFile:47)
	at com.mendix.if.a(SourceFile:193)
	at com.mendix.if.executeAction(SourceFile:148)
	at com.mendix.systemwideinterfaces.core.UserAction.execute(SourceFile:53)
	at com.mendix.core.actionmanagement.CoreAction.doCall(SourceFile:291)
	at com.mendix.core.actionmanagement.CoreAction.call(SourceFile:276)
	at com.mendix.core.actionmanagement.ActionManager.executeSync(SourceFile:205)
	at com.mendix.core.component.InternalCore.execute(SourceFile:262)
	at com.mendix.iS.a(SourceFile:135)
	at com.mendix.pf$g.apply$mcV$sp(SourceFile:292)
	at com.mendix.pf$g.apply(SourceFile:283)
	at com.mendix.pf$g.apply(SourceFile:283)
	at com.mendix.core.session.Worker$$anonfun$receive$3$$anonfun$2.apply(SourceFile:155)
	at scala.util.Try$.apply(Try.scala:191)
	at com.mendix.core.session.Worker$$anonfun$receive$3.applyOrElse(SourceFile:153)
	at akka.actor.Actor$class.aroundReceive(Actor.scala:465)
	at com.mendix.core.session.Worker.aroundReceive(SourceFile:146)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:516)
	at akka.actor.ActorCell.invoke(ActorCell.scala:487)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:238)
	at akka.dispatch.Mailbox.run(Mailbox.scala:220)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:393)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)

Caused by: com.mendix.core.CoreRuntimeException: A virtual primitive cannot be assigned a value, as it represents an action
	at com.mendix.core.objectmanagement.MendixObjectMemberImpl.setValue(SourceFile:233)
	at com.mendix.core.objectmanagement.member.MendixEnum.setValue(SourceFile:70)
	at com.mendix.core.objectmanagement.member.MendixEnum.setValue(SourceFile:21)
	at com.mendix.core.objectmanagement.MendixObjectMemberImpl.parseValueFromString(SourceFile:255)
	at com.mendix.core.objectmanagement.MendixObjectImpl.setValue(SourceFile:219)
	at com.mendix.core.objectmanagement.MendixObjectImpl.setValue(SourceFile:209)
	at objectbackuprestore.RestoreObjectsImpl.restoreObject(RestoreObjectsImpl.java:489)
	at objectbackuprestore.RestoreObjectsImpl.restoreObjects(RestoreObjectsImpl.java:113)
	at objectbackuprestore.actions.RestoreObjectsAction.executeAction(RestoreObjectsAction.java:46)
	at objectbackuprestore.actions.RestoreObjectsAction.executeAction(RestoreObjectsAction.java:21)
	at com.mendix.systemwideinterfaces.core.UserAction.execute(SourceFile:53)
	at com.mendix.core.actionmanagement.CoreAction.doCall(SourceFile:291)
	at com.mendix.core.actionmanagement.CoreAction.call(SourceFile:276)
	at com.mendix.core.actionmanagement.ActionManager.executeSync(SourceFile:205)
	at com.mendix.core.component.InternalCore.execute(SourceFile:262)
	at com.mendix.hx.execute(SourceFile:42)
	at com.mendix.ig.a(SourceFile:47)
	at com.mendix.if.a(SourceFile:193)
	at com.mendix.if.executeAction(SourceFile:148)
	at com.mendix.systemwideinterfaces.core.UserAction.execute(SourceFile:53)
	at com.mendix.core.actionmanagement.CoreAction.doCall(SourceFile:291)
	at com.mendix.core.actionmanagement.CoreAction.call(SourceFile:276)
	at com.mendix.core.actionmanagement.ActionManager.executeSync(SourceFile:205)
	at com.mendix.core.component.InternalCore.execute(SourceFile:262)
	at com.mendix.iS.a(SourceFile:135)
	at com.mendix.pf$g.apply$mcV$sp(SourceFile:292)
	at com.mendix.pf$g.apply(SourceFile:283)
	at com.mendix.pf$g.apply(SourceFile:283)
	at com.mendix.core.session.Worker$$anonfun$receive$3$$anonfun$2.apply(SourceFile:155)
	at scala.util.Try$.apply(Try.scala:191)
	at com.mendix.core.session.Worker$$anonfun$receive$3.applyOrElse(SourceFile:153)
	at akka.actor.Actor$class.aroundReceive(Actor.scala:465)
	at com.mendix.core.session.Worker.aroundReceive(SourceFile:146)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:516)
	at akka.actor.ActorCell.invoke(ActorCell.scala:487)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:238)
	at akka.dispatch.Mailbox.run(Mailbox.scala:220)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:393)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)

**Comment by mgroeneweg** [comment]
Fixed in release 1.3, it will skip virtual attributes.
